services:
  backend:
    build:
      context: ./services/backend
      dockerfile: ./Dockerfile
    container_name: "backend"
    image: backend:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    env_file:
      - ./deployment/configs/envs/backend.env
      - ./deployment/configs/envs/postgres.env
#    volumes:
#      - ./:/app/ # real time change

  db:
    build:
      context: ./services/db
      dockerfile: ./Dockerfile
    container_name: postgres
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h $$DB_HOST -p $$POSTGRES_PORT"
      interval: 2s
      timeout: 10s
      retries: 5
    env_file:
      - ./deployment/configs/envs/postgres.env
#    volumes:
#      - /tmp/web/log/postgres:/var/log/postgresql
#      - /tmp/web/db/history/:/root/psql_history/
